import { Colors } from "@/theme/theme";
import { StyleSheet } from "react-native";

export const getStyles = (colors: Colors) =>
    StyleSheet.create({
        container: {
            flexGrow: 1,
            backgroundColor: colors.background,
            alignItems: "center",
            padding: 24,
            paddingTop: 60,
            gap: 20,
            paddingBottom: 150,
        },
        titleText: {
            fontSize: 26,
            fontWeight: "700",
            color: colors.textPrimary,
        },
        subTitle: {
            fontSize: 15,
            fontWeight: "600",
            color: colors.textPrimary,
        },
        subText: {
            fontSize: 13,
            color: colors.textSecondary,
            textAlign: "justify",
        },
        sectionView: {
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            width: "100%",
            gap: 12,
            padding: 24,
            backgroundColor: colors.surface,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: colors.border,
        },
        subSectionView: {
            display: "flex",
            justifyContent: "center",
            width: "100%",
            gap: 8,
            padding: 16,
            backgroundColor: colors.surface,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: colors.border,
        },
        roundBadge: {
            paddingHorizontal: 14,
            paddingVertical: 6,
            borderRadius: 20,
            backgroundColor: colors.surfaceRaised,
            borderWidth: 1,
            borderColor: colors.border,
        },
        roundBadge2: {
            borderColor: colors.primary,
            backgroundColor: colors.primary + "18",
        },
        roundBadgeText: {
            fontSize: 12,
            fontWeight: "600",
            color: colors.textSecondary,
        },
        roundsPreview: {
            flexDirection: "row",
            width: "100%",
            alignItems: "center",
            justifyContent: "center",
            gap: 8,
        },
        roundPreviewCard: {
            flex: 1,
            alignItems: "center",
            gap: 4,
            padding: 16,
            backgroundColor: colors.surface,
            borderRadius: 14,
            borderWidth: 1,
        },
        roundPreviewEmoji: {
            fontSize: 28,
        },
        roundPreviewTitle: {
            fontSize: 14,
            fontWeight: "700",
            color: colors.textPrimary,
        },
        roundPreviewSub: {
            fontSize: 12,
            color: colors.textSecondary,
        },
        roundArrow: {
            alignItems: "center",
            justifyContent: "center",
        },
        roundIntroEmoji: {
            fontSize: 48,
        },
        movementList: {
            width: "100%",
            gap: 10,
        },
        movementRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: 12,
        },
        movementHeader: {
            flexDirection: "row",
            gap: 16,
            alignItems: "center",
        },
        movementStep: {
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: colors.surfaceRaised,
            borderWidth: 2,
            borderColor: colors.border,
            justifyContent: "center",
            alignItems: "center",
        },
        movementStepActive: {
            borderColor: colors.primary,
            backgroundColor: colors.primary + "22",
        },
        movementStepDone: {
            borderColor: colors.positive,
            backgroundColor: colors.positive + "22",
        },
        movementStepText: {
            fontSize: 14,
            fontWeight: "600",
            color: colors.textSecondary,
        },
        movementStepTextActive: {
            color: colors.primary,
        },
        movementLabel: {
            fontSize: 16,
            fontWeight: "700",
            color: colors.textPrimary,
            textAlign: "center",
        },
        movementBadge: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: colors.primary,
            justifyContent: "center",
            alignItems: "center",
        },
        movementBadgeText: {
            fontSize: 14,
            fontWeight: "700",
            color: colors.textOnPrimary,
        },
        ringContainer: {
            width: "90%",
            justifyContent: "center",
            alignItems: "center",
        },
        ringBg: {
            position: "absolute",
            width: 200,
            height: 200,
            borderRadius: 100,
            borderWidth: 8,
            borderColor: colors.border,
        },
        ringFill: {
            position: "absolute",
            bottom: -20,
            left: 0,
            height: 4,
            borderRadius: 2,
        },
        ringInner: {
            alignItems: "center",
            gap: 4,
        },
        countdown: {
            fontSize: 64,
            fontWeight: "800",
            color: colors.textPrimary,
            lineHeight: 72,
        },
        metricsRow: {
            flexDirection: "row",
            width: "100%",
            gap: 12,
        },
        metricCard: {
            backgroundColor: colors.surface,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: colors.border,
            padding: 16,
            alignItems: "center",
            gap: 4,
        },
        metricLabel: {
            fontSize: 12,
            fontWeight: "600",
            color: colors.textSecondary,
            textTransform: "uppercase",
            letterSpacing: 0.8,
        },
        metricValue: {
            fontSize: 24,
            fontWeight: "800",
            color: colors.textPrimary,
        },
        metricUnit: {
            fontSize: 11,
            color: colors.textDisabled,
        },
        hapticHint: {
            fontSize: 12,
            color: colors.primary,
            fontWeight: "500",
            textAlign: "center",
        },
        jerkBarBg: {
            width: "100%",
            height: 12,
            backgroundColor: colors.surfaceRaised,
            borderRadius: 6,
            overflow: "hidden",
        },
        jerkBarFill: {
            height: "100%",
            borderRadius: 6,
        },
        jerkBarLabels: {
            flexDirection: "row",
            justifyContent: "space-between",
            width: "100%",
        },
        cooldownEmoji: {
            fontSize: 48,
        },
        cooldownTitle: {
            fontSize: 20,
            fontWeight: "700",
            color: colors.textPrimary,
        },
        comparisonRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: 10,
            width: "100%",
        },
        comparisonLabel: {
            flex: 1,
            fontSize: 13,
            color: colors.textSecondary,
        },
        deltaBadge: {
            paddingHorizontal: 10,
            paddingVertical: 4,
            borderRadius: 10,
            borderWidth: 1,
        },
        movementResultCard: {
            width: "100%",
            gap: 10,
            padding: 16,
            backgroundColor: colors.surfaceRaised,
            borderRadius: 12,
            alignItems: "center",
        },
        resultHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: 12,
            alignSelf: "flex-start",
        },
        resultGrid: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: 10,
            width: "100%",
            justifyContent: "center",
        },
        statBox: {
            backgroundColor: colors.surface,
            borderRadius: 12,
            padding: 12,
            alignItems: "center",
            minWidth: "44%",
            gap: 2,
        },
        statLabel: {
            fontSize: 11,
            fontWeight: "600",
            color: colors.textSecondary,
            textTransform: "uppercase",
            letterSpacing: 0.6,
        },
        statValue: {
            fontSize: 20,
            fontWeight: "800",
            color: colors.textPrimary,
        },
        smoothnessBadge: {
            paddingHorizontal: 16,
            paddingVertical: 6,
            borderRadius: 20,
            borderWidth: 1,
        },
        smoothnessBadgeText: {
            fontSize: 13,
            fontWeight: "700",
            textTransform: "uppercase",
            letterSpacing: 1,
        },
        promptText: {
            fontSize: 13,
            color: colors.textSecondary,
            alignSelf: "flex-start",
            lineHeight: 20,
        },
        buttonPrimary: {
            width: "100%",
            backgroundColor: colors.primary,
            paddingVertical: 16,
            borderRadius: 14,
            alignItems: "center",
        },
        buttonPrimaryText: {
            color: colors.textOnPrimary,
            fontSize: 16,
            fontWeight: "700",
        },
        buttonSecondary: {
            width: "100%",
            backgroundColor: colors.surfaceRaised,
            paddingVertical: 16,
            borderRadius: 14,
            alignItems: "center",
            borderWidth: 1,
            borderColor: colors.border,
        },
        buttonSecondaryText: {
            color: colors.textSecondary,
            fontSize: 16,
            fontWeight: "600",
        },
    });
